[package]
name = "hello-rust"
version = "0.1.0"
authors = ["MensurOwary <mensurowary@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2"
eval = "0.4.3"
colored = "1.9.3"
rodio = "0.10.0"
